### ISSUE TITLE
Update Upgrade Advisor page to reference E-Series

### ISSUE THREAD

**Issue by roscocheeta** [NetAppDocs/active-iq#102]
Page: [Upgrade the ONTAP version by generating an upgrade plan](https://docs.netapp.com/us-en/active-iq/task_view_upgrade.html)

Now that Upgrade Advisor supports E-Series, this particular page might need to be refreshed to make that clearer.

**Comment by netapp-manishc** [comment]
Thank you for contacting us with your feedback. We are following up with the team to evaluate the inputs. After your inputs are researched internally, we will determine how best to address them and update the content at the earliest.

**Comment by netapp-manishc** [comment]
We have included information about E-Series system in the [Key Concepts](https://docs.netapp.com/us-en/active-iq/concept_key_terms.html) topic. You can find this information in the point that provides information about “Upgrades widget”.

If you have any other questions, you can reach out to us at [ng-doccomments](mailto:%3cng-doccomments@netapp.com%3e).
