### ISSUE TITLE
List file formats available for reports. 

### ISSUE THREAD

**Issue by binder1234** [NetAppDocs/active-iq#104]
Page: [Types of reports](https://docs.netapp.com/us-en/active-iq/concept_report_types.html)

The list partially indicates file formats that are available. There was a recent case where a customer was looking for a pdf for the ClusterViewer report but the only option available is excel. 

Can we update the page to list the available format types for the different reports?

**Comment by netapp-manishc** [comment]
Thank you for contacting us with your feedback. We are following up with the team to evaluate the inputs. After your inputs are researched internally, we will determine how best to address them and update the content at the earliest.

**Comment by netapp-manishc** [comment]
While creating the report, the available output formats are displayed for each report. The same is mentioned in the topic: [Generate Reports](https://docs.netapp.com/us-en/active-iq/task_generate_reports.html)
