### ISSUE TITLE
"NSS" is inappropriate for customer-facing documentation

### ISSUE THREAD

**Issue by adamn-ntap** [NetAppDocs/active-iq#107]
Page: [Manage your clusters in Cloud Manager](https://docs.netapp.com/us-en/active-iq/concept_manage_your_cluster_in_cloud_manager.html)

NSS is an internal acronym for the NetApp Support Site. We need to properly reference the site and/or the credentials that are required.

**Comment by netapp-manishc** [comment]
Thank you for bringing this to our attention. This has been fixed: [Manage your clusters in Cloud Manager](https://docs.netapp.com/us-en/active-iq/concept_manage_your_cluster_in_cloud_manager.html)
