### ISSUE TITLE
Add screenshots to steps to make it easier for customers to walk through this process. 

### ISSUE THREAD

**Issue by binder1234** [NetAppDocs/active-iq#109]
Page: [Upgrade the ONTAP version by generating an upgrade plan](https://docs.netapp.com/us-en/active-iq/task_view_upgrade.html)

See KB 
https://kb.netapp.com/Advice_and_Troubleshooting/Data_Infrastructure_Management/Active_IQ_Digital_Advisor/Where_can_I_find_instructions_to_upgrade_ONTAP

**Comment by netapp-manishc** [comment]
Thank you for contacting us with your feedback. We are evaluating your inputs regarding the usage of screenshots in the content. After your inputs are evaluated internally, we will determine how best to address the feedback.

**Comment by binder1234** [comment]
Any updates on this?

**Comment by netapp-manishc** [comment]
The topic [Upgrade the ONTAP version by generating an upgrade plan](https://docs.netapp.com/us-en/active-iq/task_view_upgrade.html) has been updated to include relevant screenshots.
