### ISSUE TITLE
Other release info

### ISSUE THREAD

**Issue by sabarig84** [NetAppDocs/active-iq#111]
Page: [What’s new in Active IQ Digital Advisor](https://docs.netapp.com/us-en/active-iq/reference_new_activeiq.html)

Hey team,

  Upgrade advisor now supports double hop, and it doesn't seemed to be added to release notes. any idea why?

**Comment by netapp-manishc** [comment]
Thank you for contacting us with your feedback. We are following up with the team to evaluate the inputs. After your inputs are researched internally, we will determine how best to address them and update the content at the earliest.

**Comment by netapp-manishc** [comment]
We have included information about Multi-hop Upgrade in the [What’s new in Active IQ Digital Advisor](https://docs.netapp.com/us-en/active-iq/reference_new_activeiq.html) topic.
