### ISSUE TITLE
Change "Take" to "Make" when describing decision making 

### ISSUE THREAD

**Issue by jenatnetapp** [NetAppDocs/active-iq#116]
Page: [Take informed decisions based on cloud recommendations](https://docs.netapp.com/us-en/active-iq/task-informed-decisions-based-on-cloud-recommendations.html)

Take informed decisions based on cloud recommendations

should be

Make informed decisions based on cloud recommendations

**Comment by jenatnetapp** [comment]
@netapp-manishc

**Comment by netapp-manishc** [comment]
@jenatnetapp Thank you for providing your feedback to help improve the content.
I have incorporated your feedback: [Make informed decisions based on cloud recommendations](https://docs.netapp.com/us-en/active-iq/task-informed-decisions-based-on-cloud-recommendations.html)
