### ISSUE TITLE
Need Clarity on Generate tokens to use APIs

### ISSUE THREAD

**Issue by hasan-05** [NetAppDocs/active-iq#117]
Page: [Generate tokens to use APIs](https://docs.netapp.com/us-en/active-iq/task_generate_tokens_API_services.html)

The page says:
You should download and save the access token and refresh token for later use. Access tokens expire one hour after generation and refresh tokens should be regenerated every 7 days and installed in the application. After 90 days, you will need to manually login and obtain a new access and refresh token.

It both says needs to be regenerated every 7 days and after 90 days we have to manually obtain the tokens, however per customer experience we see they have to obtain a refresh token every 7 days manually, if this point can be clarified, it would be a lot less work figuring this out.

There is a discussion on this for reference:
https://community.netapp.com/t5/Active-IQ-and-AutoSupport-Discussions/refresh-token/m-p/431741

**Comment by netapp-manishc** [comment]
Thank you for contacting us with your feedback. We are following up with the team to evaluate the inputs. After your inputs are researched internally, we will determine how best to address them and update the content at the earliest.

**Comment by netapp-manishc** [comment]
Refresh tokens should be regenerated every 7 days and installed in the application. You do not need to log in to the application to complete this activity. However, after 90 days, you need to log in to the application to obtain a new access and refresh token. I have updated the topic to mention this information: [Generate tokens to use APIs](https://docs.netapp.com/us-en/active-iq/task_generate_tokens_API_services.html)
