### ISSUE TITLE
external links are not tagged as such

### ISSUE THREAD

**Issue by ntap-bmegan** [NetAppDocs/active-iq#129]
### Page URL

https://docs.netapp.com/us-en/active-iq/concept_autosupport.html

### Page title

AutoSupport

### Summary

External links - ones that are not in the same repo - must be tagged with `^` notation.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by nikhilamn** [comment]
Thanks, Megan. The external links are now tagged with ^ notation:
https://docs.netapp.com/us-en/active-iq/index.html
Closing this issue.
