### ISSUE TITLE
Document the start=1& requirement 

### ISSUE THREAD

**Issue by binder1234** [NetAppDocs/active-iq#141]
### Page URL

https://docs.netapp.com/us-en/active-iq/concept_overview_API_service.html#api-catalog

### Page title

API Catalog

### Summary

In order to limit the number of responses it requires using start=1& when making API calls against the api.activeiq.netapp.com

We recently had a customer attempting to limit the responses 
https://api.activeiq.netapp.com//v1/system/inventory/details/level/customer/id/<customerid>?limit=50

The customer was informed that they had to modify the call to specify the start=1&
https://api.activeiq.netapp.com//v1/system/inventory/details/level/customer/id/<customerid>?start=1&limit=50

This requirement is not documented in any of the locations.
https://docs.netapp.com/us-en/active-iq/concept_overview_API_service.html#api-catalog
https://activeiq.netapp.com/catalog/internal/api-reference/activeiq-public/system/#get-v1-system-inventory-details-level-level-id-id
https://aiq.netapp.com/catalog/internal/docs/introduction

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-manishc** [comment]
Thank you for contacting us with your feedback. We are following up with the team to evaluate the inputs. After your inputs are researched internally, we will determine how best to address them and update the content at the earliest.

**Comment by musings-from-marz** [comment]
Was there a resolution to this issue?  Was it code or documentation change?

**Comment by netapp-manishc** [comment]
This information was updated in the UI.

**Comment by binder1234** [comment]
Where in the UI was this updated?
