### ISSUE TITLE
Can we add a note on why upgrade advisor may not show all of the available versions

### ISSUE THREAD

**Issue by binder1234** [NetAppDocs/active-iq#145]
### Page URL

https://docs.netapp.com/us-en/active-iq/task_view_upgrade.html

### Page title

Upgrade the ONTAP version of your storage systems

### Summary

Support periodically receives questions as to why customers aren't able to select the newest version of Ontap and generate an upgrade plan. 

It would be helpful to inform customers as to why this might be and what can be done. 
For example:
Platform limitation
Intermediate upgrade required
etc..

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-shwetav** [comment]
Hi @binder1234,

Thank you for letting us know. We will look into it and determine how best to address it.

Thank you again for helping us improve the quality of our documentation.

Regards,
Shweta

**Comment by netapp-shwetav** [comment]
Hi @binder1234,

The system automatically calculates the target OS version using a direct or direct multi-hop upgrade path for automated nondisruptive upgrade (ANDU). 
It is difficult to explain “why this might be and what can be done”, as numerous reasons could prevent the platform from selecting the latest version, such as an outdated controller.  For “what can be done”, you can check the Supported ONTAP upgrade paths (https://docs.netapp.com/us-en/ontap/upgrade/concept_upgrade_paths.html).
Let me know if you any more doubts.

**Comment by binder1234** [comment]
Can we add that link to the Upgrade Section in Active Digital Advisor?

**Comment by netapp-shwetav** [comment]
@binder1234: We are going to provide the link in our revised content, which will be published in the first week of January.

**Comment by netapp-shwetav** [comment]
@binder1234: The link is provided in our revised content.
It is available here: https://docs.netapp.com/us-en/active-iq/upgrade_advisor_overview.html.
