### ISSUE TITLE
Remove CVO acronym

### ISSUE THREAD

**Issue by netapp-bcammett** [NetAppDocs/active-iq#151]
### Page URL

https://docs.netapp.com/us-en/active-iq/learn_BlueXP_sustainability.html

### Page title

Learn about sustainability

### Summary

Please remove the "CVO" acronym from the note. We shouldn't use acronyms for product names.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-manishc** [comment]
I have removed the "CVO" acronym from the note: https://docs.netapp.com/us-en/active-iq/learn_BlueXP_sustainability.html
