### ISSUE TITLE
Add a note that you can check the contract/warranty dates for systems on this page. 

### ISSUE THREAD

**Issue by binder1234** [NetAppDocs/active-iq#153]
### Page URL

https://docs.netapp.com/us-en/active-iq/task_view_inventory_details.html

### Page title

View inventory details

### Summary

Currently the only reference to contracts is here
https://docs.netapp.com/us-en/active-iq/task_renew_support_contracts_for_your_systems.html

This does not give you the specific dates when the support contracts expire. 

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-shwetav** [comment]
Hi @binder1234,

Thank you for notifying us.
We will look into it and determine how best to address it.
Thanks again for helping us improve the quality of our documentation.

Regards,
Shweta

**Comment by netapp-shwetav** [comment]
@binder1234: The contract/warranty dates for systems can be viewed in the UI. This information can be found in the inventory widget by clicking Systems. It is listed under the 'Support Offering' and 'SSP Contract End Date' columns. In the documentation, we specify that you can view system-specific information by clicking Systems, which includes these columns.
