### ISSUE TITLE
Please embed this official NetApp YouTube video on this page

### ISSUE THREAD

**Issue by michaelrstewart1** [NetAppDocs/active-iq#161]
### Page URL

https://docs.netapp.com/us-en/active-iq/task_execute_ansible_playbook_without_docker.html

### Page title

Execute Ansible Playbook without NetApp Docker image

### Summary

Please embed this official NetApp YouTube video on this page
https://www.youtube.com/watch?v=lSn37FFKUfY&list=PLdXI3bZJEw7kWBxqwLYBchpMW4k9Z6Vum&index=7

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-shwetav** [comment]
Hi @michaelrstewart1,
Thank you for bringing this to our attention. We will look into it and determine how best to address it.
Thanks again for helping us improve the quality of our documentation.

Regards,
Shweta

**Comment by netapp-shwetav** [comment]
Hi @michaelrstewart1,

As discussed with you, I have decided not to embed the aforementioned video into the documentation. This video is outdated and could potentially confuse users.

Regards,
Shweta
