### ISSUE TITLE
Upgrade plans cannot be generated for out of support release. 

### ISSUE THREAD

**Issue by binder1234** [NetAppDocs/active-iq#171]
### Page URL

https://docs.netapp.com/us-en/active-iq/upgrade_advisor_overview.html

### Page title

Overview

### Summary

"For clusters running ONTAP 9.6 or older versions, you can view the information about new features and enhancements in upgrade recommendations. The pre-upgrade check report and risk summary are unavailable, and you can generate an upgrade plan in the older format."

This is no longer valid as versions prior to 9.6 are now EOS and as such, upgrade plans cannot be generated. 

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-manishc** [comment]
Thank you for contacting us with your feedback. We are following up with the team to evaluate the inputs. After your inputs are researched internally, we will determine how best to address them and update the content at the earliest.

**Comment by netapp-manishc** [comment]
This information has been removed from the topic: https://docs.netapp.com/us-en/active-iq/upgrade_advisor_overview.html
Thank you for helping improve the documentation.
