### ISSUE TITLE
Make it clear that there are two versions of AIQ?

### ISSUE THREAD

**Issue by adamn-ntap** [NetAppDocs/active-iq#29]
Page: [Overview](https://docs.netapp.com/us-en/active-iq/index.html)

I might be an outlier, but in this topic, I was looking for a short and succinct statement that there are two versions of AIQ. For example, I think we did something similar to that when we released SM.Next in 9.6. Something to consider and perhaps take to PdM for consideration.

**Comment by netapp-manishc** [comment]
Discussed with Sudip and included the following in the Overview topic. The following is staging site link: http://vmwvatapp01-stg.corp.netapp.com/active-iq/us-en/

The new version of Active IQ, known as Active IQ Digital Advisor, is simple and enables you to quickly identify and take the next best action to improve the wellness of your NetApp environment. Active IQ Digital Advisor has been enhanced and redesigned telp you perform tasks more effectively. We are incrementally enhancing this version and urge you to try out this new experience and give us your feedback at ng-activeiq-feedback@netapp.com.

**Comment by netapp-manishc** [comment]
The topic has been updated and published live:
https://docs.netapp.com/us-en/active-iq/
