### ISSUE TITLE
Request update to color/severity table. Only 3 colors are shown yet there are 4 levels of severity noted in copy.

### ISSUE THREAD

**Issue by JetMaurier** [NetAppDocs/active-iq#39]
Page: [Key concepts](https://docs.netapp.com/us-en/active-iq/concept_key_terms.html)

**Comment by netapp-manishc** [comment]
I have updated the Key concepts topic to mention the 3 levels of severity:
https://docs.netapp.com/us-en/active-iq/concept_key_terms.html
Please check

**Comment by JetMaurier** [comment]
I believe the text is correct. The table is missing a color. However, I am not the expert on this.
Judith

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
