### ISSUE TITLE
Can we put the menu items in alphabetical order?

### ISSUE THREAD

**Issue by ccataldo228** [NetAppDocs/active-iq#4]
Page: [NetApp Active IQ Documentation](https://docs.netapp.com/us-en/active-iq/index.html)

Thanks

**Comment by netapp-manishc** [comment]
Thank you for the feedback.
As discussed over email, we are looking at changing the structure of the Active IQ documentation to follow a workflow-based structure. We will incorporate your feedback as part of the restructuring.

**Comment by ccataldo228** [comment]
OK, thanks



Cory Cataldo
Product Manager
Product Tools, Analytics & Globalization Services (PTAGS)
Cloud Infrastructure Business Unit (CIBU)

MSME, PMP, Stanford APM
NetApp RTP
919.476.4978
cory.cataldo@netapp.com<mailto:cory.cataldo@netapp.com>
