### ISSUE TITLE
Can we change all non-technical ticket to non technical case pls

### ISSUE THREAD

**Issue by sudiphore** [NetAppDocs/active-iq#69]
Page: [Frequently asked questions for Active IQ](https://docs.netapp.com/us-en/active-iq/reference_aiq_faq.html)

pls change ticket to case, that's the standard term we use.

**Comment by netapp-manishc** [comment]
@sudiphore I have incorporated the changes and the following is the link to the updated topic:
https://docs.netapp.com/us-en/active-iq/reference_aiq_faq.html

**Comment by netapp-manishc** [comment]
Closing this issue as the changes have been incorporated.
