### ISSUE TITLE
Request for updating the JA translation

### ISSUE THREAD

**Issue by taiganishimura-1129** [NetAppDocs/active-iq#71]
Page: [法的通知](https://docs.netapp.com/ja-jp/active-iq/reference_legalnotices.html)
Please replace the JA translation "法的通知" with "知的財産権等について" in the title of this page.

**Comment by netapp-gudugunti** [comment]
We are evaluating options to update the translated string.

**Comment by ntap-bmegan** [comment]
This issue will be closed on tues 30 aug 2022 due to lack of activity within the last 30 days. @taiganishimura-1129 - If you believe that the original problem persists, please comment in this issue to keep it open for further review.

**Comment by ntap-bmegan** [comment]
This issue has been closed due to inactivity. Any interested party can comment to reopen the issue.
