### ISSUE TITLE
Enhancement: Add video to config drift docs

### ISSUE THREAD

**Issue by adamn-ntap** [NetAppDocs/active-iq#80]
Page: [Understand configuration deviation](https://docs.netapp.com/us-en/active-iq/concept_overview_config_drift.html)

Please consider embedding the config drift video - https://www.youtube.com/watch?v=MbkwcZ7xk3Y

Either in concept_overview_config_drift.html or in one of the other topics in the "Identify configuration deviations" section.

**Comment by netapp-manishc** [comment]
I will include the video in the Config Drift Overview topic (concept_overview_config_drift.html) and publish it for the upcoming release.
