### ISSUE TITLE
Request for documentation enhancement

### ISSUE THREAD

**Issue by Jo-Hammer** [NetAppDocs/active-iq#89]
Page: [Generate tokens to use APIs](https://docs.netapp.com/us-en/active-iq/task_generate_tokens_API_services.html)

Hi,
The documentation does not say that one loses the ability to refresh tokens after 7 days, it only says that they should be refreshed within 7 days. 
With the current behaviour one have to manually download a new refresh key every 7 days.

**Comment by netapp-manishc** [comment]
Thank you for contacting us with your feedback. We are following up with the team to evaluate the inputs. After your inputs are researched internally, we will determine how best to address them and update the content at the earliest.

**Comment by netapp-manishc** [comment]
I have updated the content to reflect the correct information. The following is the link to the topic: [Generate tokens to use APIs](https://docs.netapp.com/us-en/active-iq/task_generate_tokens_API_services.html)

**Comment by Jo-Hammer** [comment]
Hi,

Thanks. The behavior of the refresh key that you describe doesn't resonate with my findings so I need to follow up on this in the community.
It's good though that you have clarified how it is supposed to work so that we can move forward with my question.

Thanks again,

Johan



Johan Hammarström  |  
Proact IT Sweden AB
Presales Consultant
Phone: +46841066627  •  
Mobile: +46 733 56 66 27
P.O.Box 1205, 
SE-164 28 
Kista, 
Sweden  •  
Visiting address: 
Kistagången 2
#ThePowerOfData  |  
#ThePowerOfTogether
Proact processes personal information you may provide via email or otherwise in accordance with its Proact's privacy notice.ProactSE2020EX001
