### ISSUE TITLE
The product name ActiveIQ Digital Advisor is to be protected from translation

### ISSUE THREAD

**Issue by yukakou** [NetAppDocs/active-iq#90]
Page: [Active IQ デジタルアドバイザのドキュメント](https://docs.netapp.com/ja-jp/active-iq/index.html)

It may have been already reported but the product name ActiveIQ Digital Advisor is translated. It needs to be left in English in any language site.

**Comment by netapp-gudugunti** [comment]
Thanks! for reporting this issue, @yukakou. Let me check and get back to you.

**Comment by ntap-bmegan** [comment]
Closing. @yukakou has access to the development issue.
