### ISSUE TITLE
The first paragraph is not translated

### ISSUE THREAD

**Issue by yukakou** [NetAppDocs/active-iq#91]
Page: [Active IQ デジタルアドバイザのドキュメント](https://docs.netapp.com/ja-jp/active-iq/index.html)

Somehow the first paragraph is not translated:

Active IQ Digital Advisor enables you to optimize your data infrastructure across your global hybrid cloud by delivering actionable predictive analytics and proactive support through a cloud-based portal and mobile app. Active IQ"s cloud-based services leverage community wisdom and peer comparisons that are drawn from NetApp"s massive installed base, combining these insights with AutoSupport telemetry and My AutoSupport features to deliver an advanced set of unparalleled analytics services

**Comment by netapp-gudugunti** [comment]
Thanks! for reporting the issue, @yukakou. Shall review the issue and get back to you.

**Comment by ntap-bmegan** [comment]
Closing. Related development issues are showing as closed.
