### ISSUE TITLE
Missing limitations relating to the Risk Acknowledgment feature

### ISSUE THREAD

**Issue by roscocheeta** [NetAppDocs/active-iq#99]
Page: [Known limitations](https://docs.netapp.com/us-en/active-iq/reference_limitations_activeiq.html)

The risk acknowledgement feature can take hours to update the status of a risk as being "acknowledged" and same for "unacknowledged". AIQ engineering folks are aware but seems its not been documented well. Might be worth noting it down in the meantime as we wait for AIQ engineering to over-haul how this feature works to improve the performance in the future.

**Comment by netapp-manishc** [comment]
Thank you for contacting us with your feedback. We are following up with the team to evaluate the inputs. After your inputs are researched internally, we will determine how best to address them and update the content at the earliest.

**Comment by netapp-manishc** [comment]
The [Known limitations](https://docs.netapp.com/us-en/active-iq/reference_limitations_activeiq.html) topic has been updated to include information about acknowledged and unacknowledged risks.
